### ISSUE TITLE
compoundboolstatement.py - Line 6

### ISSUE THREAD

**Issue by yammesicka** [brennerm/PyTricks#18]
https://github.com/brennerm/PyTricks/blame/master/compoundboolstatement.py#L6
Absolutely would not work.
Replace with `if 1 and 6 and not 4 in l:` to see that the answer is still true.
Python will check only `if not 4 in l`, as "1 and 6" is True.

**Comment by illuz** [comment]
How will you solve of this problem?
`for 1 in l and 2 in l and 3 in l`?
Or transform them into sets and use make intersection?

**Comment by yammesicka** [comment]
You can use: `if all(map(l.__contains__, (1, 2, 3))):`, but I find it as an extremely bad practice.

**Comment by brennerm** [comment]
@yammesicka 
You're right.
Shame on me ;)
