### ISSUE TITLE
switch is not switch

### ISSUE THREAD

**Issue by yammesicka** [brennerm/PyTricks#20]
https://github.com/brennerm/PyTricks/blob/master/switch.py -
This is not fallthrough as you can expect from switch-case statement ^^"

**Comment by brennerm** [comment]
Thanks :)
Added handling if key is not in dict.

**Comment by yammesicka** [comment]
Still not switch :)
https://en.wikipedia.org/wiki/Switch_statement#Fallthrough

**Comment by brennerm** [comment]
Do you see any way to add this functionality in a pythonic way?

**Comment by brennerm** [comment]
@yammesicka 
From what I can find Python's switch case statement doesn't support fallthrough.

**Comment by yammesicka** [comment]
There are no switch case in Python as far as I know

**Comment by brennerm** [comment]
Damn you're right :D.
That's the problem switching between different languages frequently ;)

**Comment by brennerm** [comment]
updated file
