### ISSUE TITLE
Categorize/Descriptions/Index in README?

### ISSUE THREAD

**Issue by kpurdon** [brennerm/PyTricks#53]
Some method of organization, or "index" in the README might be useful. See https://github.com/vinta/awesome-python for an example.

Perhaps part of the users PR to add a trick would be to add an entry in the README?

**Comment by brennerm** [comment]
Hey, 
thanks for opening this issue. I already had the intention to structure this repo in some way, see https://github.com/brennerm/PyTricks/issues/29, but it didn't seem like there was a need for.

Do you have any suggestions which categories to choose?

**Comment by kpurdon** [comment]
Ah, I missed #29. If there is no demand then i'd just leave it as is.

**Comment by felipevolpone** [comment]
Hey guys, based on the book Fluent Python (http://shop.oreilly.com/product/0636920032519.do), we could create something like this:
1. The Python Model Objet
2. Data Structures 
   2.1 Array and Sequences
   2.2 List Comprehension 
   2.3 Tuples
   2.4 Slicing 
   2.5 Using + and \* with sequences
3. Dictionaries and sets
4. Decorators

btw, I could start this process in a different branch. What did you think?

**Comment by kpurdon** [comment]
I like the idea of following the book. It could also be interesting to follow something like the official tutorials: https://docs.python.org/2/tutorial/

**Comment by brennerm** [comment]
Hey guys, sorry for my late response.
I like the approach the book takes and created a new branch called [#53-introduce-categorization](https://github.com/brennerm/PyTricks/tree/%2353-introduce-categorization).
Feel free to add your ideas to it and open a pull request for further discussion.

I will think about it as well and add my ideas.

**Comment by felipevolpone** [comment]
Hey @brennerm, could you rename the branch? 'cause I think that will not be possible make git clone with the branch name starting with "#".

**Comment by brennerm** [comment]
Done.
https://github.com/brennerm/PyTricks/tree/issue53-introduce-categorization

**Comment by Friz-zy** [comment]
Maybe should add license explicitly in readme?

**Comment by brennerm** [comment]
Hey @Friz-zy, what's the purpose?
