### ISSUE TITLE
Add a reversestring.py file

### ISSUE THREAD

**Issue by NDevox** [brennerm/PyTricks#74]
I've made a pull request - #73.

Thought it would be worth an issue to go along side in case it warranted a discussion.

As stated in the pull request:

I think we could justify having a separate file from reverselist for reversing strings and ints.

Some newbies don't have the conceptual leap from slicing lists to slicing strings.

Other possibility is to merge the two into a reverseiterable.py but I feel this is less explicit than two separate files.

**Comment by brennerm** [comment]
I agree with your point to split the examples into two different files.

**Comment by NDevox** [comment]
Closing this as all merged in and all in agreement.
